### PR TITLE
Fix/odd 772 update message for multiple redirects

### PR DESCRIPTION
**Pull request by deoyani**
This PR contains fix to make sure redirect URLs are handled properly
Updated number of trials for redirect to 7 
When files are not included in bundle plan, appropriate message is updated

### CODE REVIEW

**Comment by RayPlante** [comment]
Regarding the tests commented out in [5496c46 ("Testing tests again!")](https://github.com/usnistgov/oar-dist-service/pull/66/commits/5496c465877d8512a9296b2de276e17e2e4515c0):  I uncommented these lines and then ran that test in isolation--i.e. with no other tests running before or after it; it still fails to report an error.  This says that the problem is not that the test is being affected by state from other tests.  Rather, the problem is most likely originating in the `DownloadBundlePlanner` class.  It is difficult to debug this through the `BundleDownloadPlanController` because it runs in a separate process and accessed via a URL.  Note that `DownloadBundlePlanner` is one of the classes that is updated in this PR.  

I noticed that the `DownloadBundlePlanner` class does not have any unit tests.  I would suggest that you create a unit test that provides the same inputs as the failing test.  You can then debug this directly and get to the source of the problem.

**Comment by deoyani** [comment]
> I noticed that the `DownloadBundlePlanner` class does not have any unit tests. I would suggest that you create a unit test that provides the same inputs as the failing test. You can then debug this directly and get to the source of the problem.

There is a unit test for DownloadBundlePlanner and the controller tests run fine if run independently. I am checking if there is any other issue in the code which is making the test fails and update the code accordingly.

**Comment by deoyani** [comment]
@RayPlante  I fixed the issue by using NIST url which returns 301 as our code checks redirected location unto 7 times, If we use example of httpstat/301, it's redirect location returns 200, which is fine to test redirects as well but we wanted to check 'error' message. All tests are working now.

**Comment by deoyani** [comment]
The code is updated to used allowed number of redirects from config server. This feature is added to use the service like https://httpstat.us to test different response codes and to make sure to limit number of redirects while testing appropriate exception or error messages. This change also needs config server change. Changes in configuration files are added in oar-config repository and new pull request(#42)  is created.

**Comment by deoyani** [comment]
Updated validationHelper, please check and see if it works. I will clean up the code and remove stale code or repetition. I will organize the code once the logic is confirmed ok.

**Comment by RayPlante** [comment]
Please fix tests.

**Comment by RayPlante** [comment]
You might find this to be a simpler implementation for `checkURLStatusLocationSize()`:

```
    private static URLStatusLocation checkURLStatusLocationSize(String url, int allowedRedirects) {

	HttpURLConnection conn = null;
	try {

            // Do a HEAD on the URL to see how it responds
	    URL obj = new URL(url);
	    conn = (HttpURLConnection) obj.openConnection();
	    HttpURLConnection.setFollowRedirects(false);
	    conn.setInstanceFollowRedirects(false);
	    conn.setConnectTimeout(10000);
	    conn.setReadTimeout(10000);
	    conn.setRequestMethod("HEAD");
	    int responseCode = conn.getResponseCode();
	    long length = conn.getContentLength();
	    String location = conn.getHeaderField("Location");

            allowedRedirects--;

            if (responseCode >= 300 && responseCode < 400 && allowedRedirects > 0) 
                // We've been redirected; try the redirected location
		return checkURLStatusLocationSize(location, allowedRedirects);

            return new URLStatusLocation(responseCode, location, url, length, true);

	} catch (IOException exp) {
	    logger.error(exp.getMessage());
	    logger.info("There is error reading this url:" + url + "\n" + exp.getMessage());
	    return new URLStatusLocation(0, url, url, 0, true);
	}
        finally {
            if (conn != null) conn.disconnect();
        }

    }
```

**Comment by deoyani** [comment]
Ray, I updated changes in the code and incorporated your suggestions as well.  Resolved one conflict and updated one test. Let me know if you see any other changes. I will create another branch for cleaner and simpler versions of some other part of the list service code. This one is working and known issues are fixed.

**Pull request merged**
