### PR TITLE
Redesigned packing code and updated tests

### PR DESCRIPTION
**Pull request by deoyani**
This Branch includes many changes related to packaging/bundle. 
The changes include:
1. Validate request before pulling data to create bundle.
2. Make sure validation is called only once and create appropriate data structure of URLs to be used ib the package/Bundle creation.
3. Eliminated some errors and issues at the validation level
4. Create BundlePlan with proper user readable messages if files are not included in the Bundle/package download plan.
5. Added new exceptions and handlers to make sure proper message is sent back to client, in case package is empty or URLs do not return proper data.
6. Updated class names, function/method names and cleaned up stale code.
7. Added and updated existing tests. 

This branch also addresses 
[ODD-752](http://mml.nist.gov:8080/browse/ODD-752)
[ODD-749](http://mml.nist.gov:8080/browse/ODD-749)

### CODE REVIEW

**Comment by RayPlante** [comment]
One way to avoid repeating expensive network calls is to cache the results the first time you make them.  

The `DataPackager` interface has `getTotalSize()` and `validateBundleRequest()`; there is nothing in the design or documentation that would suggest that these would be implemented by making a series of HEAD calls; thus, a user might assume that these are simply returning or examining local data and call them multiple times.  Since there is no reason to think that the results will be different between different calls to these functions (because they are based on the request set at construction time), there's no reason why the implementation couldn't cache the results in the first call.  That is, the `DefaultDataPackager` class could, for example, keep private variables like `Long _totsize` and `Boolean _valid` which are null to begin with; when `getTotalSize()` and `validateBundleRequest()` are called the first time, these values are set with the calculated size and `Boolean.TRUE`.  On subsequent calls, these values are returned immediately.

**Comment by deoyani** [comment]
@RayPlante 
I did not see this response message before, I will check it again in the code but I think in new version I changed the visibility of those variables.

**Comment by deoyani** [comment]
All the clean up code in tests is executed in @After function. This is executed after every test. 
Added Checks for getTotalSize and ValidateBundle to return already cached value if executed already.

**Comment by RayPlante** [comment]
I'm running this under oar-docker, and I find I can't open the zip files I download.   `unzip` complains: 
```
Archive:  download96578-1.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of download96578-1.zip or
        download96578-1.zip.zip, and cannot find download96578-1.zip.ZIP, period.
```
It seems the files are corrupted in some way.  Are the output zip files getting closed properly?

**Comment by deoyani** [comment]
@RayPlante 
There might be an issue due to merging of branches that output stream closing got messed up.
I updated code again. Tests are working fine. Let me know if you notice any other issues.

**Comment by deoyani** [comment]
@RayPlante 
I have added few more changes which include,
Return proper error messages and status code.
Make sure proper exceptions are thrown.
Updated tests according to all the changes and messages.

**Pull request merged**
