### PR TITLE
Fix Dockerfile typo causing request to install python2

### PR DESCRIPTION
**Pull request by RayPlante**
The `Dockerfile` for the `docker/build-test` container--used to build the distribution service jar--contained what appeared to be a cut-and-paste error that was resulting in an attempt to install the deprecated python2.  This PR pulls the errant lines from the `Dockerfile`.

To test, please build via oar-docker, branch=test/chips-coll-sdp, and `localdeploy`.  If the `distservice` container builds successfully, you can approve this PR.

### CODE REVIEW

**Comment by elmiomar** [comment]
Build is successful when using branch **fix/docker-build-typo**  for the **distservice** is **deployment.yml** file.

**Review by elmiomar — COMMENTED** [review]
Build is successful when using branch **fix/docker-build-typo** for the **distservice** is **deployment.yml** file.

**Comment by chuanlin2018** [comment]
I got following error this time:

#########################
#
# Building auth-py...
#
#########################
+ scripts/install.sh --install-dir=/dev/oar-auth-py/python/dist/oarauth
Installing into /dev/oar-auth-py/python/dist/oarauth...

Installing python libraries into /dev/oar-auth-py/python/dist/oarauth/lib/python...
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup, find_namespace_packages
ModuleNotFoundError: No module named 'setuptools'
localbuild: oar-auth-py: build failure: Failed to build components from oar-auth-py
localbuild: The following components failed to build:
localbuild:   oar-auth-py: build failure: Failed to build components from oar-auth-py
localbuild: Some components not available due to build failures
localdeploy: One or more needed components failed to build

**Comment by elmiomar** [comment]
> * scripts/install.sh --install-dir=/dev/oar-auth-py/python/dist/oarauth
>   Installing into /dev/oar-auth-py/python/dist/oarauth...
> 
> ModuleNotFoundError: No module named 'setuptools' 

Can you try installing **setuptools**? @chuanlin2018

**Comment by chuanlin2018** [comment]
I installed "setuptools" following this instruction:
https://www.geeksforgeeks.org/how-to-set-up-setuptools-for-python-on-macos/
But it still complained "No module named 'setuptools'".

I decided to manually build individual app. For ../scripts/localdeploy -f ingestdata, both my old and new machine got this error:

#8 1.849 Get:19 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [55.2 kB]
#8 1.855 Get:20 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [28.6 kB]
#8 1.904 Get:21 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [3933 kB]
#8 3.487 Reading package lists...
#8 5.100 W: GPG error: http://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 Release: The following signatures were invalid: EXPKEYSIG 656408E390CFB1F5 MongoDB 4.4 Release Signing Key <packaging@mongodb.com>
#8 5.100 E: The repository 'http://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 Release' is not signed.
#8 ERROR: process "/bin/sh -c apt-get update && apt-get install -y ca-certificates locales python3.8 python3-pip python3.8-dev" did not complete successfully: exit code: 100

**Comment by chuanlin2018** [comment]
../scripts/localdeploy -f ingestservice got the same error:

#8 2.869 Get:21 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [28.6 kB]
#8 3.946 Reading package lists...
#8 5.396 W: GPG error: http://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 Release: The following signatures were invalid: EXPKEYSIG 656408E390CFB1F5 MongoDB 4.4 Release Signing Key <packaging@mongodb.com>
#8 5.396 E: The repository 'http://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 Release' is not signed.
#8 ERROR: process "/bin/sh -c apt-get update && apt-get install -y ca-certificates locales python3.8 python3-pip python3.8-dev" did not complete successfully: exit code: 100

**Comment by elmiomar** [comment]
This issue was investigated previously in [oar-metadata PR#62](https://github.com/usnistgov/oar-metadata/pull/62), and Ray fixed it by upgrading to Ubuntu 22 and MongoDB 7 in [PR#63](https://github.com/usnistgov/oar-metadata/pull/63).

Maybe use a recent branch for **oar-metadata/ingestservice** component? @chuanlin2018 @RayPlante

**Comment by RayPlante** [comment]
This PR is supposed to be specifically about building oar-dist-service under oar-docker.  I'm going to take Omar's success as approval.

**Pull request merged**
